"""documents fields update

Revision ID: 9656ea6befb0
Revises: 97c0fa9a858b
Create Date: 2026-09-07 22:10:46.093441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM


# revision identifiers, used by Alembic.
revision: str = '9656ea6befb0'
down_revision: Union[str, Sequence[str], None] = '97c0fa9a858b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    document_type_enum = ENUM(
        'DOCUMENT', 'PDF', 'MEDIA',
        name='documenttype',
        create_type=True  # This creates the type
    )
    document_type_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('document_type', sa.Enum('DOCUMENT', 'PDF', 'MEDIA', name='documenttype'), nullable=False, server_default='DOCUMENT'))
    op.add_column('documents', sa.Column('file_url', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('file_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'file_metadata')
    op.drop_column('documents', 'file_url')
    op.drop_column('documents', 'document_type')
    document_type_enum = ENUM(
        'DOCUMENT', 'PDF', 'MEDIA',
        name='documenttype'
    )
    document_type_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
