"""comments table

Revision ID: b46ab8faf182
Revises: 7c96ee4f20e0
Create Date: 2026-09-05 16:35:47.198771

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b46ab8faf182'
down_revision: Union[str, Sequence[str], None] = '7c96ee4f20e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('selection', sa.JSON(), nullable=True),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('resolved', sa.Boolean(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_comments_created', 'comments', ['created_at'], unique=False)
    op.create_index('idx_comments_document', 'comments', ['document_id'], unique=False)
    op.create_index('idx_comments_parent', 'comments', ['parent_id'], unique=False)
    op.create_index('idx_comments_resolved', 'comments', ['resolved'], unique=False)
    op.create_index('idx_comments_user', 'comments', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_comments_user', table_name='comments')
    op.drop_index('idx_comments_resolved', table_name='comments')
    op.drop_index('idx_comments_parent', table_name='comments')
    op.drop_index('idx_comments_document', table_name='comments')
    op.drop_index('idx_comments_created', table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
